### PR TITLE
Improve layout of article list view: submitter name.

### PR DESCRIPTION
**Pull request by jschulenklopper**
Add margin to separate submitter name and time.

See difference in the two screen shots. Before the layout fix, the submitter name (when displayed in a wider screen so that it doesn't flow over to a next line) seems to be "panic4", but should read "panic 4 hours ago".

In order to fix that, add a 4 px (suggestion) margin to the right of `.inline-block` class.

screen shot before layout fix

screen shot after layout fix

### CODE REVIEW

**Comment by cheeaun** [comment]
Wow thanks, I didn't realise this bug somehow 😅 

I think it would be better if it's fixed by adding a space between the `<span>` elements?

**Comment by jschulenklopper** [comment]
> I think it would be better if it's fixed by adding a space between the <span> elements?

Yeah, that is an alternative solution -- perhaps better. I briefly thought about inserting a small dot, just like you did between time and number of comments, but that would look silly when the lines do break in a smaller display.

Actually, there are multiple ways to solve it:

- inserting a `&nbsp;` between the two `<span>`s in `post.mustache`
- adding a normal space after `{{user}}` within the `<span>` in `post.mustache`
- increasing the margin or padding between the two elements -- what I did in the CSS file

It is a valid / common question, with multiple solutions. See for example http://stackoverflow.com/questions/23894544/need-to-insert-space-between-inline-elements.

I guess it boils down to your preference. You can implement it either way, or state what you prefer and I will modify the PR.

**Comment by cheeaun** [comment]
Oh! I think I accidentally removed the "fix", so this is actually a regression bug. Should be like this 9b1f694d6b31e84badd90ace22bd85de5c4a23ca

Would be cool if you can change this PR. Thanks! 😄

**Comment by jschulenklopper** [comment]
OK, done. Changes in CSS files are reverted, and I've added a plain space character before the `<span>` that contains the time. It's all in this PR.

**Pull request merged**
